# .render.yaml
services:
  - type: web
    name: personal-finance-backend
    env: node
    plan: free
    region: oregon
    branch: main
    buildCommand: "npm install"
    startCommand: "node index.js"
    envVars:
      - key: DB_HOST
        value: "your-database-host"
      - key: DB_USER
        value: "your-database-username"
      - key: DB_PASS
        value: "your-database-password"
      - key: DB_NAME
        value: "finance_tracker"
      - key: DB_PORT
        value: "3306"
      - key: JWT_SECRET
        value: "your-secret-key"
      - key: GMAIL_USER
        value: "your-email@gmail.com"
      - key: GMAIL_PASS
        value: "your-app-password"
    autoDeploy: true
    plan: free
    healthCheckPath: "/"
    instanceCount: 1
    serviceDiscovery:
      internal: false

staticPublish:
  - path: ./uploads
    url: /uploads
